### PR TITLE
Fix tests on Windows and Node.js 12

### PR DESCRIPTION
**Pull request by RyanZim**
Discovered when working on https://github.com/sindresorhus/make-dir/pull/19.

Seems Node 12 returns a different error code.

### CODE REVIEW

**Comment by RyanZim** [comment]
Tests still failing, due to `xo` acting weird on Windows, refs https://github.com/sindresorhus/make-dir/pull/20. Also, seems `nyc` does not work in TravisCI Windows env.

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by sindresorhus** [comment]
I fixed the linting issue, but now it's throwing a different error: https://travis-ci.org/sindresorhus/make-dir/jobs/649422483#L74

**Comment by RyanZim** [comment]
@sindresorhus TravisCI is using `nvs` for Node version management on Windows, which places `node` at a non-standard location, and breaks `nyc` on Windows, hence the error.

**Comment by sindresorhus** [comment]
https://travis-ci.org/sindresorhus/make-dir/builds/649549579?utm_medium=notification&utm_source=github_status

**Pull request merged**
